"""about author added

Revision ID: 16655a7b01ce
Revises: 7b899a0baaf0
Create Date: 2023-12-03 12:05:47.068678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16655a7b01ce'
down_revision = '7b899a0baaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
